#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 Yusuke Oka
# SPDX-License-Identifier: BSD-3-Clause

import sys
import random
import time

def main():
    try:
        # ラウンド数取得
        rounds = 0
        for line in sys.stdin:
            rounds = int(line.strip()) # 整数に変換
            if rounds < 0:
                raise ValueError("ラウンド数は０以上の整数にしろ。") # 例外（-1など）
            break
    except ValueError as e:
        if "invalid literal" in str(e): # エラーメッセージに"invalid literal"があるか。整数に変換するところで無効な値（aなど）をうってるか。
            print("正しい数字を入力しろ。（０以上の整数）") # aと打ったときのエラー
        else:
            print(e) # -1と打ったときのエラー
        sys.exit(1) # エラー終了

    play_game(rounds)

def play_game(rounds):
    directions = ['上','下','左','右']
    print("ゲームスタート")
    for i in range(rounds):
        print(f"\nゲーム{i + 1}")    
        print("あっち向いてホイ")
        time.sleep(3)
        print(f"　-> {random.choice(directions)}")
        time.sleep(2)

    print("\n終了")


if __name__ =="__main__":
    main()




