#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 Yusuke Oka
# SPDX-License-Identifier: BSD-3-Clause

import sys
import random
import time

def main():

        print("ゲームスタート")
        rounds = 0
        for line in sys.stdin:
            rounds = int(line.strip())
            break
        play_game(rounds)

def play_game(rounds):
    directions = ['上','下','左','右']

    for i in range(rounds):
        print(f"\nゲーム{i + 1}")


if __name__ =="__main__":
    main()
    
