#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 Yusuke Oka
# SPDX-License-Identifier: BSD-3-Clause

import sys
import random  
import time


def main():
    
        print("遊ぶ回数を数字で入力してね:")

if __name__ =="__main__":
    main()


