#!/usr/bin/bash -xv
# SPDX-FileCopyrightText: 2024 Yusuke Oka
# SPDX-License-Identifier: BSD-3-Clause

ng () {
        echo ${1}行目が違うよ
        res=1

}

res=0

# 正常な入力のテスト
out=$(echo 3 | ./k1)
[[ "$out" == *"ゲームスタート"* && "$out" == *"終了"* && "$out" == *"ゲーム"* && "$out" == *"あっち向いてホイ"* ]] || ng "$LINENO"

out=$(echo 0 | ./k1)
[[ "$out" == *"ゲームスタート"* && "$out" == *"終了"* ]] || ng "$LINENO"

# 無効な入力（文字列と空白）のテスト
out=$(echo a | ./k1)
[[ "$out" == *"正しい数字を入力しろ。（０以上の整数）"* ]] || ng "$LINENO"

out=$(echo abc | ./k1)
[[ "$out" == *"正しい数字を入力しろ。（０以上の整数）"* ]] || ng "$LINENO"

out=$(echo   | ./k1)
[[ "$out" == *"正しい数字を入力しろ。（０以上の整数）"* ]] || ng "$LINENO"

out=$(echo ! | ./k1)
[[ "$out" == *"正しい数字を入力しろ。（０以上の整数）"* ]] || ng "$LINENO"

out=$(echo あ | ./k1)
[[ "$out" == *"正しい数字を入力しろ。（０以上の整数）"* ]] || ng "$LINENO"















[ "${res}" = 0 ] && echo OK
exit $res


