#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 Yusuke Oka
# SPDX-License-Identifier: BSD-3-Clause

import sys
import random  
import time


def main():

        print("ゲームスタート")

if __name__ =="__main__":
    main()


